# Doppler configuration for rennan-tech-landing
setup:
  project: rennan-tech
  config: prd

# Environment mappings
environments:
  development:
    project: rennan-tech
    config: dev
  staging:
    project: rennan-tech
    config: stg
  production:
    project: rennan-tech
    config: prd