name: rennan-site

services:
  rennan-site:
    image: ${ECR_REPOSITORY_URI:-rennan-site}:latest
    container_name: rennan-site
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - lightsail-public

networks:
  lightsail-public:
    name: lightsail-public
    external: true
